-- Student Learning
INSERT INTO PERFORMANCE_REVIEW VALUES ('A' , 'SL' , 'SP1' , 'I believe {teacher}''s teaching methods are very innovative and effective. The class scores are consistently improving. {teacher} continuously utilizes technology provided by the school to improve the student''s learning experience.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('A' , 'SL' , 'SP2' , '{teacher}''s students actively participate in class discussions even when the topics are new and advanced. I think the learning environment that {teacher} creates in the classroom will continue to help improve the student''s scores and academic achievements.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('B' , 'SL' , 'SP1' , '{teacher} regularly evaluates the classroom and uses the evaluation to focus on material that students find most tricky. This helps students develop academically by focusing on topics that are most challenging for them.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('B' , 'SL' , 'SP2' , 'While {teacher}''s class doesn''t rank high on standard exams, we should focus on the relative improvement of the class''s performance over the past 4 years. I believe {teacher}''s teaching style will continue to prove valuable in improving student learning.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('C' , 'SL' , 'SP1' , 'I recommend that {teacher} utilize alternative methods of teaching such as using visual aids to facilitate explaining difficult concepts to students. I believe that remains an area for development.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('C' , 'SL' , 'SP2' , '{teacher}''s students have shown lower rates of participation than their peers in other classes. I recommend that {teacher} focus on developing a more engaging environment in the classroom to improve students'' participation and interest in the topics.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('D' , 'SL' , 'SP1' , '{teacher} has demonstrated ability of maintaining an inclusive learning environment and an engaging teaching style. Students actively participate in {teacher}''s class and continue to show improved academical skills.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('D' , 'SL' , 'SP2' , 'I think {teacher} has done a good job at improving the class''s academic performance against difficult conditions. I trust {teacher} will continue learning new teaching methods and developing a stronger academic cohort.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('E' , 'SL' , 'SP1' , '{teacher} continuously adjusts teaching style by closely monitoring students'' evaluations and scores. This has allowed the teacher to detect failing methods early and develop feedback based methods that address the students'' academic needs.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('E' , 'SL' , 'SP2' , '{teacher} has not shown initiative to handle students with special needs. I recommend developing one-on-one relations with the students to closely evaluate their skills in class.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('F' , 'SL' , 'SP1' , 'I think {teacher} should give more attention to introverted students and try to encourage them to participate in class discussions. An inclusive classroom environment is a must for every successful educator.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('F' , 'SL' , 'SP2' , 'The students in {teacher}''s class have consistently scored well on standard exams and continue to compete with their peers in different schools. {teacher} continuously encourages the students to go further and try harder.');
-- Instructional Practice
INSERT INTO PERFORMANCE_REVIEW VALUES ('A' , 'IP' , 'SP1' , '{teacher} demonstrates enthusiasm, involvement, and interest in lesson presentation. The teacher communicates clearly, provides students with individual feedback, and continuously evaluates the classroom and adjusts instructional practice accordingly.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('A' , 'IP' , 'SP2' , '{teacher} has very strong organizational skills. The objectives of every class are always laid out at the beginning of the class allowing students to follow through with ease. {teacher} engages the students with exercises and provides timely and individual feedback to every student.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('B' , 'IP' , 'SP1' , 'I have no major concerns about {teacher}''s instructional skills. {teacher}''s teaching methods consistently promote team work and group discussion making the classroom more exciting for students.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('B' , 'IP' , 'SP2' , 'I recommend that {teacher} take more time with students especially with new and advanced topics. I think that''s an area of development that still needs improvement.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('C' , 'IP' , 'SP1' , '{teacher} adheres closely to the curriculum, demonstrates great flexibility with planning, and pays close attention to student learning. {teacher} demonstrates strong knowledge of the class material and is always prepared.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('C' , 'IP' , 'SP2' , 'I would recommend that {teacher} develop instructional practices to encourage participation, especially from shy kids. During my visits to {teacher}''s classroom, students did not participate in class discussions as expected.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('D' , 'IP' , 'SP1' , 'I recommend that {teacher} be more assertive and strict in the classroom. I think the students were poorly controlled in few instances.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('D' , 'IP' , 'SP2' , 'I think {teacher} can improve further on monitoring student''s learning, especially the quite ones in class. A clear transition between topics can help all students remain interested.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('E' , 'IP' , 'SP1' , '{teacher} has shown improved skills at preparing class material and planning classes ahead of time. This has allowed the students to learn more effectively. I trust {teacher} will continue developing into an effective educator.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('E' , 'IP' , 'SP2' , '{teacher} has a strong presence in the classroom, demands students'' respect, and manages disruptive behavior constructively.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('F' , 'IP' , 'SP1' , '{teacher} maintains a well suited and inclusive learning environment. The classroom is always under control allowing students to learn more effectively. {teacher} does a great job at exciting students and engaging them in group exercise and class discussions.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('F' , 'IP' , 'SP2' , '{teacher} has a very strong and confident presense in the classroom. This was an area of development during the first two years. But by accepting contructive feedback and actioning on it, {teacher} has shown capacity for developing effective instructional practices.');
-- Professionalism
INSERT INTO PERFORMANCE_REVIEW VALUES ('A' , 'PF' , 'SP1' , 'I expect {teacher} to get more involved with initiatives in terms of planning and preparation of training events and other professional activities.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('A' , 'PF' , 'SP2' , '{teacher} should focus on developing professional maturity especially with accepting critical feedback. I think {teacher} is defensive towards criticism necessary for professional growth.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('B' , 'PF' , 'SP1' , 'Last year {teacher} volunteered to set up the Professional Education workshop held for teachers at the school. Initiatives like these continue to show {teacher}''s potential as a successful and professional educator.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('B' , 'PF' , 'SP2' , 'On multiple occasions I have witnessed {teacher} take great initiative to develop close relations with students'' parents. {teacher} has also been very active with teacher\parents activities promoting a climate of open communication.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('C' , 'PF' , 'SP1' , '{teacher}''s involvement with school activities has been below expectations. In terms of communication, I recommend {teacher} be more timely in communicating classroom updates to the administration and report concerns as soon as they surface.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('C' , 'PF' , 'SP2' , '{teacher}''s commitment to developing a career in education is hardly doubtable. {teacher} routinely reflects on career growth and development plans. By actively seeking feedback, {teacher} has developed a variety of professional skills such as networking and communication.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('D' , 'PF' , 'SP1' , '{teacher} has conducted meetings with faculty and parents in a very professional manner. Two years ago {teacher} has shown great maturity during an unfortunate incident with one of the student''s parents by strictly adhering to the school''s policies and regulations.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('D' , 'PF' , 'SP2' , '{teacher} continuously takes initiative in promoting the school''s reputation by being involved with school led activities in the community. {teacher}''s participation in such activities the past year has been integral to the success of the events.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('E' , 'PF' , 'SP1' , '{teacher} has grown impressively over the years through actively seeking feedback and taking proper actions for development. A tenured teacher is one committed to growing a career in education and that is something I expect of {teacher}.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('E' , 'PF' , 'SP2' , 'During our last teacher-parent conference, {teacher} appeared distracted. Some parents complained that they didn''t get full attention from {teacher} when discussing the students. Such behavior puts the school at serious reputation risk.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('F' , 'PF' , 'SP1' , '{teacher} has provided a climate which fosters communication between the teacher and parents allowing the parents to be more closely involved with the student''s plans and interests.');
INSERT INTO PERFORMANCE_REVIEW VALUES ('F' , 'PF' , 'SP2' , '{teacher} has been very closely engaged with the school community, something we expect from our tenured faculty. I encourage {teacher} to continue with enthusiastic involvment with school activities');