-- Teacher A
insert into PERFORMANCE_REVIEW values ('A','SL','SP1','${teacher} has proven, over the past four years, capable of enhancing the students'' learning experience and promoting participation in the classroom. During the times I attended her classes, the majority of her students were actively participting in the class discussion.');
insert into PERFORMANCE_REVIEW values ('A','SL','SP2','I have no major concerns about ${teacher}''s teaching skills to recommend against promotion. However, I do think that ${teacher}, if promoted, will need to focus her efforts on developing methods for delivering difficult content to the students.');
insert into PERFORMANCE_REVIEW values ('A','SL','SP3','I think ${teacher} has succeeded in improving the class''s academic performance against difficult conditions. I have no good reason to believe that ${teacher} won''t continue learning new teaching methods and developing a stronger academic cohort.');
insert into PERFORMANCE_REVIEW values ('A','IP','SP1','${teacher} has shown improved skills at preparing class material and planning classes ahead of time. This has allowed the students to learn more effectively. I trust ${teacher} will continue developing into an effective educator.');
insert into PERFORMANCE_REVIEW values ('A','IP','SP2','${teacher} has a strong and confident presense in the classroom. This was an area of development during the first two years. But by accepting contructive feedback and actioning on it, ${teacher} has shown capacity for developing effective instructional practices.');
insert into PERFORMANCE_REVIEW values ('A','IP','SP3','I have witnessed ${teacher} learn and grow and I have little reason to believe that ${teacher} won''t continue to do so. I recommend spending more time on planning for classes ahead of time and adhering closely to the curiculum. I think ${teacher} has a promising potential.');
insert into PERFORMANCE_REVIEW values ('A','PF','SP1','${teacher} has been very closely engaged with the school community, something we stronly expect from our tenured faculty. I encourage ${teacher} to continue with enthusiastic involvment with school activities');
insert into PERFORMANCE_REVIEW values ('A','PF','SP2','I think ${teacher} is an effective communicator. ${teacher} constantly updates faculty with class condition and curiculum progress. I, however, noticed that ${teacher}''s communication with parents needs improvment. The teacher\parent conference is an excellent opportunity to prove that.');
insert into PERFORMANCE_REVIEW values ('A','PF','SP3','${teacher} continuously takes initiative in promoting the school''s reputation by being involved with school led activities in the community. ${teacher}''s participation in such activities the past year has been integral to the success of the events.');
-- Teacher B
insert into PERFORMANCE_REVIEW values ('B','SL','SP1','${teacher} is an effective educator. The students in ${teacher}''s class have consistently scored well on the state''s standard exams and continue to compete with their peers in different schools. ${teacher} continuously encourages the students to go further and try harder.');
insert into PERFORMANCE_REVIEW values ('B','SL','SP2','I recommend that ${teacher} utilize alternative methods of teaching such as using visual aids to facilitate explaining difficult concepts to students. While ${teacher} has developed a broader set of teaching techniques, I believe that remains an area for development. I trust ${teacher} will continue improving and growing.');
insert into PERFORMANCE_REVIEW values ('B','SL','SP3','${teacher}''s teaching style encourages class discussion and participation. I have witnessed student''s participation in rather complicated discussions in ${teacher}''s classroom. Students'' scores on standardized tests continue to improve with ${teacher}''s guidance.');
insert into PERFORMANCE_REVIEW values ('B','IP','SP1','${teacher} maintains a well suited and inclusive learning environment. The classroom is always under control allowing students to learn more effectively. ${teacher} does a good job at exciting students and engaging them in group exercise and class discussions.');
insert into PERFORMANCE_REVIEW values ('B','IP','SP2','I have attended ${teacher}''s classes multiple times and I can attest to the healthy learning environment that the students enjoy in the classroom. I would recommend that ${teacher} further encourage participation, especially from shy kids. ${teacher} still has a way to go, but I have no good reason to doubt future success.');
insert into PERFORMANCE_REVIEW values ('B','IP','SP3','I think ${teacher} can further improve on class preparation, especially with classes that introduce new and advanced concepts. ${teacher} continues to improve as an instructor and, with continuous development, has the potential to become a successful educator.');
insert into PERFORMANCE_REVIEW values ('B','PF','SP1','${teacher} has proved capable of communicating effectively with faculty and parents, and maintaining healthy relations. I recommend that ${teacher} do more in order to develop presence as a leader at school through more active engagement with the school community.');
insert into PERFORMANCE_REVIEW values ('B','PF','SP2','I think ${teacher} should spend more time developing a career plan. During my time as a supervisor I we had only few meetings for discussing career development. Otherwise, ${teacher} has significantly grown professionally and improved.');
insert into PERFORMANCE_REVIEW values ('B','PF','SP3','I expect that ${teacher} would continue to develop professional maturity especially with accepting critical feedback. I think ${teacher} is sensitive to criticism necessary for professional growth. ${teacher} has potential that can be materialized with consistent commitment to professionalism and career development.');
-- Teacher C
insert into PERFORMANCE_REVIEW values ('C','SL','SP1','${teacher} has consistently shown during the last couple of years ability to improve students'' scores on standardized exams. Virtually all students showed improvement, highlighting ${teacher}''s equal focus on students with different needs.');
insert into PERFORMANCE_REVIEW values ('C','SL','SP2','${teacher} has shown initiative by repeatedly reaching out to other teachers with higher experience for advice on improving teaching skills. I believe ${teacher} will further help students to improve their sores on standardized tests.');
insert into PERFORMANCE_REVIEW values ('C','SL','SP3','I think ${teacher}''s students have shown lower rates of participation than their peers in other classes. However, I have no reason to doubt that ${teacher} will continue to work to reach their promising teaching potential. ');
insert into PERFORMANCE_REVIEW values ('C','IP','SP1','${teacher} has shown great capacity for learning quickly. Teacher 2 is well knowledgeable of the curriculum and plans classes accordingly. I recommend that ${teacher} be more assertive and strict in the classroom. I felt the classroom was poorly controlled in few instances.');
insert into PERFORMANCE_REVIEW values ('C','IP','SP2','The students show respect and well behavior in ${teacher}''s classes. I think ${teacher} can improve further on monitoring student''s learning including the quite ones in class. A clear transition between topics can help all students remain interested.');
insert into PERFORMANCE_REVIEW values ('C','IP','SP3','${teacher} has strong organizational skills. The objectives of every class are always laid out at the beginning of the class allowing students to follow through with ease. ${teacher} engages the students with exercise and provides timely and individual feedback to every student.');
insert into PERFORMANCE_REVIEW values ('C','PF','SP1','I recommend that ${teacher} continue to build closer relations with parents and keep them closely updated with the students'' state. While continually improving, ${teacher}''s communication skills still need further development.');
insert into PERFORMANCE_REVIEW values ('C','PF','SP2','Last year ${teacher} volunteered to set up the Professional Education workshop held for teachers at the school. Initiatives like these continue to show ${teacher}''s potential as a successful and professional educator.');
insert into PERFORMANCE_REVIEW values ('C','PF','SP3','Compared to three years ago ${teacher} has developed a lot professionally through involvement with professional associations and committees inside and outside the school. ${teacher} is very timely in communicating school related items to the administration.');
-- Teacher D
insert into PERFORMANCE_REVIEW values ('D','SL','SP1','${teacher} has on multiple occasions utilized technology to explain difficult concepts to students. I think such initiative is important for developing teaching skills and highlights ${teacher}''s commitment to improving the students'' learning experience');
insert into PERFORMANCE_REVIEW values ('D','SL','SP2','Teaching 4 holds the students to high expectations. There is still room for development on the standardized exams, but I believe with ${teacher}''s guidance and innovative teaching skills, the students will continue to improve.');
insert into PERFORMANCE_REVIEW values ('D','SL','SP3','I have noticed that students that are quite in other classes are more active in ${teacher}''s classroom discussions. ${teacher} delivers complex content in a manner that makes it easy for students to absorb. That has been evident in the student''s improved scores.');
insert into PERFORMANCE_REVIEW values ('D','IP','SP1','${teacher} adheres closely to the curriculum, demonstrates flexibility with planning, and pays close attention to student learning. I recommend that ${teacher} encourages further group work with students.');
insert into PERFORMANCE_REVIEW values ('D','IP','SP2','${teacher} is enthusiastic which makes the classes more engaging. However, I noticed on multiple occasions that some students in the classroom do not participate as expected and are often distracted. I recommend ${teacher} pays more attention to students with special needs.');
insert into PERFORMANCE_REVIEW values ('D','IP','SP3','${teacher} demonstrates strong knowledge of the class material and is always prepared. I recommend that ${teacher} take more time with students especially with new and advanced topics. I think that''s an area of development that still needs to improvement.');
insert into PERFORMANCE_REVIEW values ('D','PF','SP1','${teacher}''s involvement with school activities has greatly improved. In terms of communication, I recommend ${teacher} be more timely in communicating classroom updates to the administration and report concerns as soon as they surface.');
insert into PERFORMANCE_REVIEW values ('D','PF','SP2','On multiple occasions I have witnessed ${teacher} take great initiative to develop close relations with students'' parents. ${teacher} has also been very active with teacher\parents activities promoting a climate of open communication.');
insert into PERFORMANCE_REVIEW values ('D','PF','SP3','By cooperating with other teachers, the administration, and other educational personnel on professional matters, ${teacher} has proven a very valuable team player. I think ${teacher} is a great positive influence on students and teachers.');
-- Teacher E
insert into PERFORMANCE_REVIEW values ('E','SL','SP1','${teacher} continues to push the students to perform better on standardized scores. ${teacher}''s class average on standardized exams, however, is still below expectations. I believe the class will continue to improve under ${teacher}''s guidance');
insert into PERFORMANCE_REVIEW values ('E','SL','SP2','I certainly appreciate ${teacher}''s efforts at ensuring an inclusive environment in the classroom. ${teacher} has done a good job at making sure that all students receive adequate amount of attention especially those struggling with the material. This has helped increase scores of the bottom quarter of the class over the years.');
insert into PERFORMANCE_REVIEW values ('E','SL','SP3','${teacher} regularly evaluates the classroom and uses the evaluation to focus on material that students are finding most tricky. While this is highly encouraged, on some occasions it deviated attention, from other material that was more critical for the standard exams.');
insert into PERFORMANCE_REVIEW values ('E','IP','SP1','I have no major concerns about ${teacher}''s instructional skills. ${teacher}''s teaching methods consistently promote team work and group discussion making the classroom more exciting for students. I think ${teacher} has a promising future as an effective educator.');
insert into PERFORMANCE_REVIEW values ('E','IP','SP2','${teacher} has a strong presence in the classroom, demands students'' respect, and manages disruptive behavior constructively. I recommend that ${teacher} spends more time with students individually in order to better evaluate students and provide proper feedback.');
insert into PERFORMANCE_REVIEW values ('E','IP','SP3','${teacher} is highly knowledgeable of the class material and the curriculum. Judging from the participation rate, students seem to fully understand the material. ${teacher}''s instructional methods successfully promote classroom discussions and group work.');
insert into PERFORMANCE_REVIEW values ('E','PF','SP1','${teacher} has shown great potential for growth throughout the years. I have recommended that ${teacher} get more involved with outside activities to promote the school. ${teacher}''s involvement with several committees has been noticed and appreciated.');
insert into PERFORMANCE_REVIEW values ('E','PF','SP2','${teacher} remains very active with the students'' parent always communicating with parents in the best interest of the students. Parents are happy with ${teacher} and consistently provide positive feedback.');
insert into PERFORMANCE_REVIEW values ('E','PF','SP3','I think ${teacher} has consistently shown professional conduct and potential for growth. ${teacher} has taken advantage of educational opportunities at the school provided for teacher to further build their teaching skills');
-- Teacher F
insert into PERFORMANCE_REVIEW values ('F','SL','SP1','Few parents have complained about their children missing fundamental concepts in ${teacher}''s class.  I don''t doubt that ${teacher} is a hard worker, and will continue to develop inclusive and engaging teaching style');
insert into PERFORMANCE_REVIEW values ('F','SL','SP2','While ${teacher}''s class doesn''t rank very high on standard exams, we should focus on the relative improvement of the class''s performance over the past 4 years. I believe ${teacher}''s teaching style will continue to prove valuable in improving student learning.');
insert into PERFORMANCE_REVIEW values ('F','SL','SP3','${teacher} has proven ability to simplify complex new concepts to students. On multiple occasions ${teacher} provided close and focused one-on-one support to students who were having difficulties during class.');
insert into PERFORMANCE_REVIEW values ('F','IP','SP1','${teacher} demonstrates enthusiasm, involvement, and interest in lesson presentation. The teacher communicates clearly and provides students with individual feedback. ${teacher} continuously evaluates the classroom and adjusts instructional practice accordingly.');
insert into PERFORMANCE_REVIEW values ('F','IP','SP2','During all my visits to ${teacher}''s classroom, the environment has always been one suitable for learning. The students were actively participating in class discussion and group work. ${teacher} sets high expectations to for the students and pushes them to achieve it.');
insert into PERFORMANCE_REVIEW values ('F','IP','SP3','${teacher} communicates clearly. Class objectives are well presented and students are continuously evaluated and provided with constructive feedback to improve the learning experience in the classroom.');
insert into PERFORMANCE_REVIEW values ('F','PF','SP1','${teacher} joined our school four years ago with little experience in education. Today, I believe, Teacher 1 has grown professionally and developed a variety of skills that makes for a reliable educator.');
insert into PERFORMANCE_REVIEW values ('F','PF','SP2','I recommend that ${teacher} get more involved with initiatives in terms of planning and preparation of the training events and other professional activities. Otherwise ${teacher} has worked hard at developing lasting relations with parents and has been a very effective communicator.');
insert into PERFORMANCE_REVIEW values ('F','PF','SP3','${teacher} showed professional maturity by effectively handling a conflict between two other teachers in school. Such maturity is appreciated and expected of tenured faculty. I trust teacher with continue to grow and participate in development and review of the school''s policies and regulations.');
-- Teacher G
insert into PERFORMANCE_REVIEW values ('G','SL','SP1','${teacher} has demonstrated ability of maintaining an inclusive learning environment and an engaging teaching style. Students actively participate in ${teacher}''s class and continue to show improvements academically.');
insert into PERFORMANCE_REVIEW values ('G','SL','SP2','I believe ${teacher}''s teaching methods are innovative and effective. The class scores are consistently improving. ${teacher} utilizes technology provided by school to improve the student''s learning experience.');
insert into PERFORMANCE_REVIEW values ('G','SL','SP3','I would like to see ${teacher} pay closer attention to shy and quite students. I recommend developing one-on-one relations with the student to closely evaluate their skills in class. I believe teacher 7''s teaching skills will continue to develop and improve.');
insert into PERFORMANCE_REVIEW values ('G','IP','SP1','${teacher} improved greatly in terms of preparation and presentation skills. This allows ${teacher} to maintain a productive learning environment for the students in the class. One area that I think ${teacher} needs to improve at is with disciplining skills I felt the classroom was out of control on few occasions');
insert into PERFORMANCE_REVIEW values ('G','IP','SP2','I think ${teacher} does a great job organizing and preparing material ahead of every lesson. The teacher utilizes a variety of methods to deliver lessons and provides direct feedback to students in a timely and clear manner.');
insert into PERFORMANCE_REVIEW values ('G','IP','SP3','It is clear that ${teacher} has improved a lot since joining our school. Students seem to be more engaged with the material this is largely due to ${teacher}''s increased awareness of the students in the classroom and the development of close relations with students, especially the ones with special needs');
insert into PERFORMANCE_REVIEW values ('G','PF','SP1','${teacher} has conducted meetings with faculty and parents in a very professional manner. Two years ago ${teacher} has shown great maturity during an unfortunate incident with one of the student''s parents by strictly adhering to the school''s policies and regulations.');
insert into PERFORMANCE_REVIEW values ('G','PF','SP2','${teacher} has grown a lot professionally by actively seeking feedback and guidance from experienced teachers and supervisors. Such attitude for continuous development is very valuable as it encourages other teachers to be more involved in continued education as well.');
insert into PERFORMANCE_REVIEW values ('G','PF','SP3','${teacher} is a professional inside and outside of the classroom. ${teacher} participates in professional workshops, attends professional meetings, and keeps current in subject area. I believe ${teacher} will continue to work on developing closer relations with parents.');
-- Teacher H
insert into PERFORMANCE_REVIEW values ('H','SL','SP1','I believe ${teacher}''s teaching methods are innovative and effective. The class scores on standardized tests continue to improve and rank competitively with peers in other classes. Students seems to enjoy the classroom learning experience.');
insert into PERFORMANCE_REVIEW values ('H','SL','SP2','I recommend that ${teacher} give more attention to introverted students and try to encourage them to participate in class discussions. Inclusion in such discussions is essential for a successful learning experience.');
insert into PERFORMANCE_REVIEW values ('H','SL','SP3','${teacher} continuously adjusts teaching style by closely monitoring students evaluations and scores. This has allowed the teacher to detect failing methods early and develop feedback based methods that address the students'' academic needs.');
insert into PERFORMANCE_REVIEW values ('H','IP','SP1','Some of the hardest things teachers must do, in my opinion, is maintain an inclusive teaching environment. This is done not only through constant presence in the classroom, but also through continued planning and preparation. I think ${teacher} has done a good job on both.');
insert into PERFORMANCE_REVIEW values ('H','IP','SP2','When it comes to clear communication of class objectives I think teacher 4 does a good job. I would, however, advice that ${teacher} adhere more closely to the curriculum when preparing classes.');
insert into PERFORMANCE_REVIEW values ('H','IP','SP3','One thing that I''ve noticed in ${teacher}''s classroom is the active involvement of the students with the class material. Students seem to be enjoying ${teacher}''s presentation methods which encourages team work and participation in class work.');
insert into PERFORMANCE_REVIEW values ('H','PF','SP1','${teacher} has great communication and presentation skills. However, during our last teacher\parent conference, ${teacher} appeared distracted. It is very important to the success of the school that parents are given full attention and kept closely updated about their student''s progress.');
insert into PERFORMANCE_REVIEW values ('H','PF','SP2','${teacher}''s commitment to developing a career in education is hardly doubtable. ${teacher} routinely reflects on career growth and development plans. By actively seeking feedback, ${teacher} has developed a variety of professional skills such as networking and communication.');
insert into PERFORMANCE_REVIEW values ('H','PF','SP3','${teacher} has provided a climate which fosters communication between the teacher and parents allowing the parents to be more closely involved with the student''s plans and interests.');
-- Teacher I
insert into PERFORMANCE_REVIEW values ('I','SL','SP1','I think ${teacher}''s students over the past 4 years had high potential. I believe ${teacher} can push the students harder to help them achieve more academically. That can be done by spending more one on one time with the students.');
insert into PERFORMANCE_REVIEW values ('I','SL','SP2','Students of ${teacher} actively participate in class discussions even when the topics are new and advanced. I think the learning environment that ${teacher} creates in the classroom will continue to help improve the student''s scores and academic achievements.');
insert into PERFORMANCE_REVIEW values ('I','SL','SP3','${teacher}''s students'' scores continue to improve on standardized tests. Score improvements are evident across the board signaling effectiveness of the teacher''s teaching style at reaching the entire classroom especially students with special needs.');
insert into PERFORMANCE_REVIEW values ('I','IP','SP1','${teacher} promotes self-discipline. Students behave very well in the classroom, which is constantly an environment suitable for learning. ${teacher} showed maturity dealing with discipline problems in accordance with policies and regulations.');
insert into PERFORMANCE_REVIEW values ('I','IP','SP2','I attest to ${teacher}''s presentation and preparation abilities. Lessons are clearly explained allowing students to follow easily and participate with class discussions. Teacher 3''s classroom is well controlled to provide for a strong learning environment.');
insert into PERFORMANCE_REVIEW values ('I','IP','SP3','${teacher} has shown great capacity for improvement in regards to class preparation and presentation. One thing I would recommend however is for ${teacher} to spend more effort making classroom instructions more accessible to all students, especially with new concepts that are known difficult for students');
insert into PERFORMANCE_REVIEW values ('I','PF','SP1','${teacher} is very actively involved with professional growth activities like participation in committees, professional meetings and workshops. This has afforded ${teacher} a strong reputation not only among fellow teachers and school administrators, but also with parents.');
insert into PERFORMANCE_REVIEW values ('I','PF','SP2','${teacher} has grown impressively over the years through actively seeking feedback and taking proper actions for development. A tenured teacher is one committed to growing a career in education and that is something I expect of ${teacher}.');
insert into PERFORMANCE_REVIEW values ('I','PF','SP3','${teacher} has maintained a good relation with students'' parents through close involvement with teacher\parent conferences and closer communication with the parents. Such behavior is welcome and expected of tenured faculty.');
