logging:
  level: INFO
  appenders:
      - type: console
server:
  rootPath: /api/
  requestLog:
      appenders:
        - type: console
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 5005